### ISSUE TITLE
Dev - Information Architecture

### ISSUE THREAD

**Issue by skipjack** [webpack/webpack.js.org#1519]
> Summing up the key points from #438...

As we continue our work on #1258, #1386, and the others mentioned in #1380, we can, and have already, started talking about better ways to group, consolidate, and improve the flow of pages within this site. This should be started by simply sorting the pages within each section, but, once we've done that, we could likely group sections within the sidebar (as suggested by @pastelsky in #438) or add another layer of navigation.

Here's the checklist of TODOs:

- [ ] Sort all existing pages in an intuitive way (already done for guides, see #1258)
- [ ] _Support_, _Development_, and maybe sponsors/backers => _Contribute_ (#1365)
- [ ] _CLI_ nav link should be removed (it will instead just be found under _API_)
- [ ] The articles should then be organized via nested directories or a `group` field.
- [ ] Top level pages should use a wider layout (e.g. #1367)

Certain infrastructure changes should make some of this much easier. Specifically the fact that in newer versions of Antwar as well as in Phenomic and Gatsby -- routing is automatically synchronized/based on the structure of the `/content` directory. This means far less configuration and a more intuitive repository. This has already been started in #980 with some antwar/webpack updates.

See the proposed nesting levels in [this comment](https://github.com/webpack/webpack.js.org/issues/438#issuecomment-282508376). As mentioned above, a `group` field in the YAML frontmatter would also help us achieve this but wouldn't be reflected in the routing structure.

**Comment by skipjack** [comment]
@montogeek if you could spare any time helping push #980 forward, that would be fantastic. All we really need to figure out at this point is the `section.all()` data that we use for the sidebars. I can help on this side of the fence, but with your antwar experience (and I'm sure @bebraw would help us along), I think we could finally get that done.

**Comment by skipjack** [comment]
@johnstew I think with #1258 we actually have gotten to a pretty good flow for the __Guides__ section (can still be improved with some simple grouping -- probably just a separation between __Basic__ and __Advanced__ as we dropped all the third-party content). However, if you have time, we would love your help with the sorting the other sections.

If you have ideas on __Concepts__ suggest them in #1386. For anything else, just list ideas here or ping me on gitter.

**Comment by montogeek** [comment]
@skipjack WIll take a look
