### ISSUE TITLE
Webpack 4 - optimization section under configuration

### ISSUE THREAD

**Issue by EugeneHlushko** [webpack/webpack.js.org#1968]
- [x] (#2053) Create the section itself
- [x] (#2053) minimize
- [x] (#2053) minimizer (for custom options reference webpack/webpack#6879)
- [x] (#2053) splitChunks
- [x] (#2112) runtimeChunk
- [x] (#2112) noEmitOnErrors
- [x] (#2271) namedModules
- [x] (#2271) namedChunks
- [ ] (#2456 WIP) portableRecords
- [x] (#2139) nodeEnv (also closes #2138)
- [x] (#2273) removeAvailableModules
- [x] (#2295) removeEmptyChunks
- [x] (#2295) mergeDuplicateChunks
- [x] (#2306) flagIncludedChunks
- [x] (#2345) occurrenceOrder
- [x] (#2392) sideEffects
- [x] (#2345) providedExports
- [x] (#2345) usedExports
- [x] (#2353) concatenateModules
- [x] (#2265) mangleWasmImports

**Comment by jeremenichelli** [comment]
Is the intention to tackle some examples on best solutions? Or simply explain configurations of each option? I'm getting the feeling that this could generate duplicated content easily if we are not careful.

**Comment by EugeneHlushko** [comment]
The plan was to mention these things and what they are doing, what options are available and what the defaults are. Do you think the list should be extended or shortened @jeremenichelli ?

**Comment by jeremenichelli** [comment]
My fear is to have duplicated references for the same content, but we can always give it a try and see if it does work. There are config that naturally are already present like the plugins for example, so it owuld be good to breifly describe them and link to their proper page, but extend the content on the ones that actually have no other explanation on the site.

**Comment by EugeneHlushko** [comment]
I got your point, yes everything that has its core page from the list above will be only briefly mentioned and linked to 👍 i did not understand your concern from the first time 😓 😆 @jeremenichelli 
P.S. picking this up soon, was busy IRL

**Comment by jeremenichelli** [comment]
@EugeneHlushko don't worry man, all good. Let me know when you have something, I'll checkout the PR and give it a look locally to see how the final content looks.

**Comment by Aqours** [comment]
`sideEffects` section is very puzzling.

```js
// src/index.ts
import './polyfills';
export function f() {}


// src/polyfills.ts
import 'promise-polyfill/src/polyfill';
import 'reflect-metadata'; // npm package
```
The above content is my TypeScript code.

```json
// config1
// package.json
{
  "sideEffects": [
    "src/polyfills.ts"
  ],
}
```

```json
// config2
// package.json
{
  "sideEffects": [
    "src/index.ts"
  ],
}
```
The bundle file include `polyfills.ts` and `promise-polyfill` and `reflect-metadata` npm packages when I use `config1`, but exclude `polyfills.ts` and `promise-polyfill` and `reflect-metadata` npm packages when I use `config2`.

I think `sideEffects` section should account for why `config1` include sub-import files and `config2` does not. We need more details.

**Comment by jeremenichelli** [comment]
@Aqours can you put this in a separate issue, I don't it belongs to this discussion and tell us what would work for you better as content in that section. Thanks in advance!

**Comment by montogeek** [comment]
All done!
